### ISSUE TITLE
Doesn't install Puppet dependencies

### ISSUE THREAD

**Issue by alexmuller** [alphagov/pp-development#17]
Need to run `bundle install && bundle exec librarian-puppet install` in `pp-puppet` while setting up.

**Comment by tombooth** [comment]
Ruby: https://github.com/alphagov/pp-development/blob/master/tools/bootstrap-vagrant#L52
Puppet: https://github.com/alphagov/pp-development/blob/master/tools/bootstrap-vagrant#L63

**Comment by alexmuller** [comment]
The README doesn't specify to run that script…

**Comment by tombooth** [comment]
Vagrant does it for you
