### ISSUE TITLE
What version of Ruby should I be using?

### ISSUE THREAD

**Issue by alexmuller** [alphagov/pp-development#18]
We don't specify. Is that a problem?

**Comment by jabley** [comment]
Will hopefully fall out of our focused testing for application in a box.

**Comment by pwaller** [comment]
Can this be closed?

**Comment by pwaller** [comment]
Also, there exists [`.ruby-version`](https://github.com/alphagov/pp-development/blob/master/.ruby-version).

**Comment by robyoung** [comment]
Yes
