### ISSUE TITLE
Can't tell if the vagrant VM has been correctly provisioned

### ISSUE THREAD

**Issue by pwaller** [alphagov/pp-development#38]
I've run it twice having destroyed the machine from the first attempt and cleaned out my `~/sw/gds` directory. I'm on Ubuntu 12.04.4, Vagrant 1.3.4 and VirtualBox 4.2.18.

I see some kernel error messages in dmesg but I can't tell if they are causally linked to the provisioning.

To help others in the future, importantly, it would be useful if the instructions stated what I should expect to see when everything is working normally.
- Does the output look normal?
- Shouldn't I see puppet provisioning messages somewhere?
- Why isn't `/var/apps` correctly mounted? 
- Are there any other things I can test?

Here's the output of following the instructions on the repository.

```
$~/sw/gds/pp-development$ GOVUK_DEPS=true ./install.sh 
---> Checking prerequisite software
OK: Found git program
OK: Found vagrant program
---> Fetching pp-development repository
OK: Skipping pp-development - already cloned
---> Reading list of public repositories from GH_REPOS and fetching from GitHub
---> Reading list of GOV.UK repositories from GOV_REPOS and fetching from GitHub
$~/sw/gds/pp-development$ ls
Gemfile       GHE_REPOS  GOV_REPOS   install.sh  Procfile   run_in.sh  update-git.sh
Gemfile.lock  GH_REPOS   hiera.yaml  Pinfile     README.md  tools      Vagrantfile
$~/sw/gds/pp-development$ vagrant up
Bringing machine 'pp-development-1' up with 'virtualbox' provider...
[pp-development-1] Importing base box 'puppetlabs-ubuntu-server-12042-x64-vbox4210-nocm'...
[pp-development-1] Matching MAC address for NAT networking...
[pp-development-1] Setting the name of the VM...
[pp-development-1] Clearing any previously set forwarded ports...
[pp-development-1] Creating shared folders metadata...
[pp-development-1] Clearing any previously set network interfaces...
[pp-development-1] Preparing network interfaces based on configuration...
[pp-development-1] Forwarding ports...
[pp-development-1] -- 22 => 2222 (adapter 1)
[pp-development-1] Running 'pre-boot' VM customizations...
[pp-development-1] Booting VM...
[pp-development-1] Waiting for machine to boot. This may take a few minutes...
[pp-development-1] Machine booted and ready!
[pp-development-1] Setting hostname...
No error message
$~/sw/gds/pp-development$ vagrant ssh
Welcome to Ubuntu 12.04.2 LTS (GNU/Linux 3.5.0-23-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Wed Apr 10 14:18:39 2013 from 10.0.2.2
vagrant@pp-development-1:~$ ls /var/apps
ls: cannot access /var/apps: No such file or directory
```

**Comment by pwaller** [comment]
I've sat down with @robyoung, and the version of virtualbox needed is wrong in the README.

It's also rather important to get the right version, so maybe the documentation could highlight this better.

See also:

https://github.com/alphagov/pp-development/commit/f348fcddfe4b9c45a0fd0f789645c0ff414c28ca

**Comment by pwaller** [comment]
Another issue is that the new version of virtualbox (4.3.6) isn't supported by vagrant 1.3.4 at least. It seems that the documentation needs to be updated to state that vagrant 1.4 is required.

**Comment by pwaller** [comment]
We'll be submitting a pull request to fix these issues and improve the situation for the future. Just having to download an image at an excruciating rate to test it, first..

**Comment by pwaller** [comment]
I think the cause of this was a bug in vagrant and virtualbox. Vagrant had exit status "1" with red text "No error message". Virtualbox kernel panicked presumably due to incompatible guest additions in the image.

**Comment by pwaller** [comment]
Next problem.

```
[pp-development-1] Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 10.0.0.1:'/home/pwaller/sw/gds' /var/apps

Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: access denied by server while mounting 10.0.0.1:/home/pwaller/sw/gds


```

**Comment by pwaller** [comment]
From the syslog:

```
Mar  4 18:01:44 uranus rpc.mountd[25167]: Cannot export /home/pwaller/sw/gds, possibly unsupported filesystem or fsid= required
Mar  4 18:01:48 uranus rpc.mountd[25167]: authenticated mount request from 10.0.0.100:919 for /home/pwaller/sw/gds (/home/pwaller/sw/gds)
Mar  4 18:01:48 uranus rpc.mountd[25167]: qword_eol: fflush failed: errno 22 (Invalid argument)
Mar  4 18:01:48 uranus rpc.mountd[25167]: Cannot export /home/pwaller/sw/gds, possibly unsupported filesystem or fsid= required
```

Will figure it out tomorrow.

**Comment by pwaller** [comment]
This latest problem is that [my home directory uses ecryptfs, which isn't supported by NFS, apparently](http://serverfault.com/questions/409639/nfs-with-encrypted-ubuntu-home-directory). I'll just disable NFS in my setup for now and see where I get.

**Comment by robyoung** [comment]
We should bias for stability rather than performance. If NFS doesn't work in all situations but does perform a lot better when it does work we should make it switchable.
