### ISSUE TITLE
bowl not installed

### ISSUE THREAD

**Issue by pwaller** [alphagov/pp-development#41]
The README says to run `bowl X`, but bowl doesn't start off installed.

It seems as though it is missing a few steps (or they are buried deeply in some other READMEs).

**Comment by alexmuller** [comment]
Hmm, [bowler should be installed by Puppet](https://github.com/alphagov/pp-puppet/blob/jenkins-performanceplatform_puppet-408/hieradata/role-development.yaml#L90) on the VM. Needs looking in to.

**Comment by pwaller** [comment]
This is buried deeply in the provisioning log. It wasn't obvious to me at the time that it was important (again with #38).

```
Error: Execution of '/usr/bin/gem install --include-dependencies --no-rdoc --no-ri bowler' returned 1: ERROR:  Error installing bowler:
[bootstrap] foreman requires dotenv (>= 0.7)
[bootstrap] INFO:  `gem install -y` is now default and will be removed
[bootstrap] INFO:  use --ignore-dependencies to install only the gems you list
[bootstrap] 
[bootstrap] Error: /Stage[main]//Node[default]/Package[bowler]/ensure: change from absent to present failed: Execution of '/usr/bin/gem install --include-dependencies --no-rdoc --no-ri bowler' returned 1: ERROR:  Error installing bowler:
[bootstrap] foreman requires dotenv (>= 0.7)
[bootstrap] INFO:  `gem install -y` is now default and will be removed
[bootstrap] INFO:  use --ignore-dependencies to install only the gems you list
[bootstrap] 
```

**Comment by jabley** [comment]
I had a quick look:

``` bash
sudo /usr/bin/gem install --include-dependencies --no-rdoc --no-ri bowler
```

works fine once you've `ssh`-ed onto the VM.

Curious.

**Comment by alexmuller** [comment]
@robyoung and I were _just_ talking about this. We think we've found the issue.

https://projects.puppetlabs.com/issues/17616

**Comment by pwaller** [comment]
@jabley, I had exactly the same experience. So why is puppet failing? All of the errors in #46 make it hard to tell exactly what's going wrong.

**Comment by pwaller** [comment]
@alexmuller 

Annoying, this seems to be a recurring theme with puppet. Not only is everything split across two bug trackers, but puppetlabs/puppet#1484 and puppetlabs/puppet#1485 (linked from https://projects.puppetlabs.com/issues/17616) have no apparent followup.

**Comment by robyoung** [comment]
The solution that GOV.UK follow is just avoid bundler for puppet runs. I'm going to investigate this as an option this afternoon.

**Comment by pwaller** [comment]
[Link to the `bundler puppet` in question](https://github.com/alphagov/pp-development/commit/d6e847b1b5b4f58419b545b648f7194944f3c2ef#diff-ad6242a248ad890ac10fff548ce946f9R77). @robyoung for my education, what was the original rationale for using bundler here?

**Comment by robyoung** [comment]
Bundler does stuff differently when you pass `--deployment`, I vaguely remember this causing problems.

**Comment by robyoung** [comment]
@pwaller are you happy for me to close this now?

**Comment by pwaller** [comment]
Yes, I'll reopen if this recurs.
