### ISSUE TITLE
/home/vagrant/.virtualenvs/*/bin/activate: No such file or directory

### ISSUE THREAD

**Issue by pwaller** [alphagov/pp-development#44]
This keeps happening. @paulfurley I understand you have a more permanent solution than manually deleting it?

```
vagrant@pp-development-1:/var/apps/pp-development$ bowl performance
I, [2014-03-05T13:55:29.513378 #2948]  INFO -- : Starting screenshot_as_a_service, spotlight, data_out, backdrop_read, backdrop_write, backdrop_admin, backdrop, stagecraft, performance..
13:55:29 screenshot_as_a_service.1 | started with pid 2951
13:55:29 spotlight.1               | started with pid 2953
13:55:29 backdrop_read.1           | started with pid 2956
13:55:29 backdrop_write.1          | started with pid 2958
13:55:29 backdrop_admin.1          | started with pid 2962
13:55:29 stagecraft.1              | started with pid 2965
13:55:29 screenshot_as_a_service.1 | Installing Node.js dependencies...
13:55:29 spotlight.1               | Installing Node.js and Ruby dependencies...
13:55:29 backdrop_read.1           | /var/apps/backdrop/start-app.sh: line 21: /home/vagrant/.virtualenvs/backdrop-read-3038/bin/activate: No such file or directory
13:55:29 backdrop_write.1          | waiting for startup lock
13:55:29 backdrop_admin.1          | waiting for startup lock
13:55:29 backdrop_read.1           | exited with code 1
13:55:29 system                    | sending SIGTERM to all processes
13:55:29 screenshot_as_a_service.1 | terminated by SIGTERM
13:55:29 spotlight.1               | terminated by SIGTERM
13:55:29 backdrop_write.1          | terminated by SIGTERM
13:55:29 backdrop_admin.1          | terminated by SIGTERM
13:55:29 stagecraft.1              | terminated by SIGTERM
```

**Comment by fawkesley** [comment]
See https://github.com/alphagov/backdrop/pull/251/files and
https://github.com/alphagov/stagecraft/pull/66

On 5 March 2014 13:56, Peter Waller notifications@github.com wrote:

> This keeps happening. @paulfurley https://github.com/paulfurley I
> understand you have a more permanent solution than manually deleting it?
> 
> vagrant@pp-development-1:/var/apps/pp-development$ bowl performance
> I, [2014-03-05T13:55:29.513378 #2948]  INFO -- : Starting screenshot_as_a_service, spotlight, data_out, backdrop_read, backdrop_write, backdrop_admin, backdrop, stagecraft, performance..
> 13:55:29 screenshot_as_a_service.1 | started with pid 2951
> 13:55:29 spotlight.1               | started with pid 2953
> 13:55:29 backdrop_read.1           | started with pid 2956
> 13:55:29 backdrop_write.1          | started with pid 2958
> 13:55:29 backdrop_admin.1          | started with pid 2962
> 13:55:29 stagecraft.1              | started with pid 2965
> 13:55:29 screenshot_as_a_service.1 | Installing Node.js dependencies...
> 13:55:29 spotlight.1               | Installing Node.js and Ruby dependencies...
> 13:55:29 backdrop_read.1           | /var/apps/backdrop/start-app.sh: line 21: /home/vagrant/.virtualenvs/backdrop-read-3038/bin/activate: No such file or directory
> 13:55:29 backdrop_write.1          | waiting for startup lock
> 13:55:29 backdrop_admin.1          | waiting for startup lock
> 13:55:29 backdrop_read.1           | exited with code 1
> 13:55:29 system                    | sending SIGTERM to all processes
> 13:55:29 screenshot_as_a_service.1 | terminated by SIGTERM
> 13:55:29 spotlight.1               | terminated by SIGTERM
> 13:55:29 backdrop_write.1          | terminated by SIGTERM
> 13:55:29 backdrop_admin.1          | terminated by SIGTERM
> 13:55:29 stagecraft.1              | terminated by SIGTERM
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/alphagov/pp-development/issues/44
> .

## 

Paul M Furley
07791 891 343

**Comment by pwaller** [comment]
Since those two have been merged I'm closing this one for now.
