### ISSUE TITLE
Foreman doesn't correctly cleanup processes on failure

### ISSUE THREAD

**Issue by pwaller** [alphagov/pp-development#48]
If I `bowl performance` and it fails, for example like this:

```
I, [2014-03-05T18:15:56.938606 #4806]  INFO -- : Starting spotlight, data_out, backdrop_read, backdrop_write, backdrop_admin, backdrop, stagecraft, performance..
18:15:57 spotlight.1               | started with pid 4809
18:15:57 backdrop_read.1           | started with pid 4811
18:15:57 backdrop_write.1          | started with pid 4813
18:15:57 backdrop_admin.1          | started with pid 4816
18:15:57 stagecraft.1              | started with pid 4819
18:15:57 spotlight.1               | Installing Node.js and Ruby dependencies...
18:15:57 backdrop_read.1           | /var/apps/backdrop/start-app.sh: line 21: /home/vagrant/.virtualenvs/backdrop-read-3038/bin/activate: No such file or directory
18:15:57 backdrop_write.1          | waiting for startup lock
18:15:57 backdrop_admin.1          | waiting for startup lock
18:15:57 backdrop_read.1           | exited with code 1
18:15:57 system                    | sending SIGTERM to all processes
18:15:57 spotlight.1               | terminated by SIGTERM
18:15:57 backdrop_write.1          | terminated by SIGTERM
18:15:57 backdrop_admin.1          | terminated by SIGTERM
18:15:57 stagecraft.1              | terminated by SIGTERM
```

Then the processes aren't terminated (despite the SIGTERM messages):

For example:

```
$ ps aux |& grep python
vagrant   4852  0.2  5.3  80940 26892 pts/0    S    18:15   0:00 python manage.py runserver 0.0.0.0:3204
vagrant   4862  2.1  5.9 161188 29848 pts/0    Sl   18:15   0:04 /home/vagrant/.virtualenvs/stagecraft/bin/python manage.py runserver 0.0.0.0:3204
```

This is a bug in foreman but it is rather annoying because when you fix the problem and try again you encounter

```
17:52:46 stagecraft.1              | Error: That port is already in use.
17:52:46 stagecraft.1              | exited with code 1
```

**Comment by pwaller** [comment]
This is related to #50.

**Comment by pwaller** [comment]
This foreman issue looks related: ddollar/foreman#384

**Comment by pwaller** [comment]
The `start-app.sh` scripts should probably `exec` the server processes. That might actually fix this issue since the right process will be signalled.

**Comment by pwaller** [comment]
Fix is incoming.

**Comment by pwaller** [comment]
Ah, it requires a fix locally and it requires ddollar/foreman#428. :frowning:

**Comment by pwaller** [comment]
I've submitted four (almost) identical pull requests to fix this from our side: [backdrop](https://github.com/alphagov/backdrop/issues/254) [spotlight](https://github.com/alphagov/spotlight/issues/273) [screenshot-as-a-service](https://github.com/alphagov/screenshot-as-a-service/issues/5) [stagecraft](https://github.com/alphagov/stagecraft/issues/76).

The [problem with foreman](https://github.com/ddollar/foreman/pull/428) remains.

**Comment by pwaller** [comment]
So the exec problem is now fixed GDS-side and the remaining issue is in foreman. @robyoung where are you guys at with the decision to fix/fork/otherwise foreman?

**Comment by robyoung** [comment]
Nowhere further really. I had a brief look at goreman but it doesn't seem to have exactly the same interface as foreman so it wouldn't be a simple lift and shift. I'm less convinced about forking foreman, we wouldn't have control over it in rubygems. What would be really nice is if @ddollar could add some maintainers or transfer ownership.

**Comment by pwaller** [comment]
By the way, one reason this might not ordinarily be much of an issue is if you send CTRL-C to the terminal then all processes in the terminal receive a SIGINT. It's only when foreman sends signals that the orphans are created.

**Comment by pwaller** [comment]
Foreman just got a massive update, and I believe this is fixed!
