### ISSUE TITLE
Error: Load timeout for modules

### ISSUE THREAD

**Issue by pwaller** [alphagov/pp-development#59]
Just encountered the following error trying to run `bowl performance`.

It was working recently and AFAIK nothing has changed since then.

I've just tried `vagrant halt` and `vagrant up` to try again and it is reproducible.

```
14:45:53 spotlight.1               | Error: Load timeout for modules: d3loader!_unnormalized4,d3loader!
14:45:53 spotlight.1               | http://requirejs.org/docs/errors.html#timeout
14:45:53 spotlight.1               |     at makeError (/var/apps/spotlight/node_modules/requirejs/bin/r.js:397:17)
14:45:53 spotlight.1               |     at checkLoaded (/var/apps/spotlight/node_modules/requirejs/bin/r.js:923:23)
14:45:53 spotlight.1               |     at Object.context.completeLoad (/var/apps/spotlight/node_modules/requirejs/bin/r.js:1787:17)
14:45:53 spotlight.1               |     at Function.req.load (/var/apps/spotlight/node_modules/requirejs/bin/r.js:2510:17)
14:45:53 spotlight.1               |     at Object.context.load (/var/apps/spotlight/node_modules/requirejs/bin/r.js:1858:21)
14:45:53 spotlight.1               |     at Object.Module.load (/var/apps/spotlight/node_modules/requirejs/bin/r.js:1059:29)
14:45:53 spotlight.1               |     at Object.Module.fetch (/var/apps/spotlight/node_modules/requirejs/bin/r.js:1049:66)
14:45:53 spotlight.1               |     at Object.Module.check (/var/apps/spotlight/node_modules/requirejs/bin/r.js:1079:26)
14:45:53 spotlight.1               |     at Object.Module.enable (/var/apps/spotlight/node_modules/requirejs/bin/r.js:1376:22)
14:45:53 spotlight.1               |     at Object.context.enable (/var/apps/spotlight/node_modules/requirejs/bin/r.js:1730:39)
14:45:53 spotlight.1               | DEBUG: Program node app/server exited with code 8
```

**Comment by pwaller** [comment]
Okay, I think this might have been that the machine I am on is slightly loaded. It now works again. Yuck.

**Comment by pwaller** [comment]
Closing this for now, but if someone finds their way to this issue again maybe it's worth finding a way to increase the timeout or something.

**Comment by alexmuller** [comment]
We've got a story in our backlog to deal with this, but it is a very intermittent issue (probably on machines that are slower/loaded, as you note).

[The timeout is in Spotlight](https://github.com/alphagov/spotlight/blob/release_310/Gruntfile.js#L13), but we've found with other external devs that increasing it doesn't necessarily fix anything.

**Comment by pwaller** [comment]
Cool. I thought I'd just get it noted in the issues here, since that's where I first looked for it.

**Comment by pwaller** [comment]
I'm reopening this since the problem has returned.

**Comment by pwaller** [comment]
Bump, still happening frequently, sometimes preventing me from demoing.

**Comment by pwaller** [comment]
After talking to @tombooth and @easternbloc, we found this may be a problem in supervisor.

**Comment by pwaller** [comment]
I can work around it by running `node app/server.js` for now at the expense of not having automatic reloading for application changes.

**Comment by pwaller** [comment]
I just hit this issue _despite_ using the workaround above.

**Comment by pwaller** [comment]
I think this time it's because I've just run a few backdrop-ga-collector, which caused my dev virtual machine to be memory deprived, and therefore swappy and just slow.

**Comment by pwaller** [comment]
I've added `vb.memory = 1536` under the `c.vm.provider :virtualbox`. Hopefully I'll end up in swapland less frequently.

**Comment by pwaller** [comment]
I can't provoke spotlight into starting at all at the moment, even with the workaround.
